/*
 * Copyright (C) 2015 Jared Boone, ShareBrained Technology, Inc.
 * Copyright (C) 2016 Furrtek
 *
 * This file is part of PortaPack.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

// This file was generated by make_bitmap.py

#ifndef __BITMAP_HPP__
#define __BITMAP_HPP__

#include "ui.hpp"

namespace ui {

static constexpr uint8_t bitmap_gps_sim_data[] = {
	0x00, 0x00, 
	0x00, 0x00, 
	0x40, 0x06, 
	0x20, 0x00, 
	0x10, 0x10, 
	0x08, 0x10, 
	0x00, 0x20, 
	0x00, 0x00, 
	0x08, 0x00, 
	0x08, 0x00, 
	0x08, 0x10, 
	0x10, 0x00, 
	0x40, 0x0C, 
	0xC0, 0x02, 
	0x00, 0x00, 
	0x00, 0x00, 
};
static constexpr Bitmap bitmap_gps_sim {
	{ 16, 16 }, bitmap_gps_sim_data
};


} /* namespace ui */

#endif/*__BITMAP_HPP__*/
